server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://142.93.163.186:5432/mentorship
    username: postgres
    password: root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 2MB