server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mentorship_dev
    username: postgres
    password: husan
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
  sql:
    init:
      mode: never