server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB-PORT:5432}/${DB_NAME:shifotop_db}
    username: postgres
    password: ${DB_PASSWORD:84310108}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
  sql:
    init:
      mode: never
  main:
    allow-circular-references: true